### ISSUE TITLE
Broken? please update?

### ISSUE THREAD

**Issue by rekkersNZ** [pregnantboy/bigtube#14]
Trying to install from chrome store - invalid manifest - wont install

if installed manually - the extention doesnt work, does not expand in the entire window like it used to..

![Screenshot from 2023-06-29 09-11-59](https://github.com/pregnantboy/bigtube/assets/61595424/61af8a8a-b36d-49b5-8371-1926465e5666)

**Comment by pinakipb2** [comment]
Fixed at https://github.com/pregnantboy/bigtube/pull/15

**Comment by rekkersNZ** [comment]
Sweet, tried that  fix, works a charm..

**Comment by pregnantboy** [comment]
Merged. Release underway
