### ISSUE TITLE
Broken again

### ISSUE THREAD

**Issue by rekkersNZ** [pregnantboy/bigtube#18]
![Screenshot from 2023-08-19 08-50-35](https://github.com/pregnantboy/bigtube/assets/61595424/20976cdf-83d3-4555-94ff-2f60970da275)
Youtube has updated something and its broken again

**Comment by pregnantboy** [comment]
fix has been made. just waiting for chrome store to review.

**Comment by rekkersNZ** [comment]
All fixed.. cheers again... ignore those twats on the chrome-store being negative...
